const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const yen=v=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(v);
const fmt=v=>new Intl.DateTimeFormat('ja-JP',{month:'short',day:'numeric'}).format(new Date(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c]);
let data={settings:{},customers:[],estimates:[],account:{}}, filter='all', authMode='login', installPrompt=null;
async function api(path,o={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(o.headers||{})},...o}),p=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(p.error||'通信に失敗しました。');e.status=r.status;throw e}return p}
async function load(){try{data=await api('/api/state');$('#authScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');render()}catch(e){$('#authScreen').classList.remove('hidden');$('#appShell').classList.add('hidden');if(e.status!==401)toast(e.message)}}
async function save(){data=await api('/api/state',{method:'PUT',body:JSON.stringify({settings:data.settings,customers:data.customers,estimates:data.estimates})});render()}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('visible');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('visible'),2500)}
function view(n){$$('.view').forEach(v=>v.classList.toggle('active',v.id===n+'View'));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===n));scrollTo({top:0,behavior:'smooth'})}
function render(){const now=new Date(),monthly=data.estimates.filter(x=>{const d=new Date(x.createdAt);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});$('#todayLabel').textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(now);$('#monthlySales').textContent=yen(monthly.filter(x=>x.paid).reduce((s,x)=>s+x.total,0));$('#unpaidTotal').textContent=yen(data.estimates.filter(x=>!x.paid).reduce((s,x)=>s+x.total,0));$('#estimateCount').textContent=monthly.length+'件';plan();estimates($('#recentEstimates'),data.estimates.slice().reverse().slice(0,3));customers();records()}
function plan(){const a=data.account||{},b=$('#planBadge'),m=$('#planMessage');if(a.plan==='standard'){b.textContent='スタンダード';m.textContent='すべての機能をご利用いただけます。';return}if(a.plan==='past_due'){b.textContent='支払い確認中';m.textContent='決済情報をご確認ください。';return}if(a.plan==='inactive'){b.textContent='解約済み';m.textContent='利用を再開するにはプランへお申し込みください。';return}const d=Math.max(0,Math.ceil((new Date(a.trialEndsAt)-new Date())/86400000));b.textContent='無料体験';m.textContent=d?'無料期間はあと'+d+'日です。':'無料期間が終了しました。'}
function estimates(c,list){if(!list.length){c.innerHTML='<div class="empty-state">まだ見積もりがありません。</div>';return}c.innerHTML=list.map(x=>`<button class="estimate-card" data-estimate="${x.id}"><div><h4>${esc(x.customerName)}</h4><p>${fmt(x.createdAt)} ・ ${esc(x.items[0]?.name||'作業')}</p><span class="status ${x.paid?'paid':''}">${x.paid?'入金済み':'未入金'}</span></div><strong>${yen(x.total)}</strong></button>`).join('');$$('[data-estimate]',c).forEach(b=>b.onclick=()=>openEstimate(b.dataset.estimate))}
function customers(){const q=$('#customerSearch').value.trim().toLowerCase(),list=data.customers.filter(c=>[c.name,c.phone,c.address].join(' ').toLowerCase().includes(q)),box=$('#customerList');if(!list.length){box.innerHTML='<div class="empty-state">条件に合うお客さまはいません。</div>';return}box.innerHTML=list.map(c=>`<button class="customer-card" data-customer="${c.id}"><div><h4>${esc(c.name)}</h4><p>${esc(c.phone||'電話番号なし')}</p><p>${esc(c.address||'住所なし')}</p></div><strong>${data.estimates.filter(x=>x.phone&&x.phone===c.phone).length}件</strong></button>`).join('');$$('[data-customer]',box).forEach(b=>b.onclick=()=>useCustomer(b.dataset.customer))}
function records(){estimates($('#recordList'),data.estimates.slice().reverse().filter(x=>filter==='all'||(filter==='paid'?x.paid:!x.paid)))}
function addItem(name='',price=''){const r=$('#itemTemplate').content.firstElementChild.cloneNode(true);$('.item-name',r).value=name;$('.item-price',r).value=price;$('.item-price',r).oninput=total;$('.remove-item',r).onclick=()=>{r.remove();if(!$$('.item-row',$('#itemRows')).length)addItem();total()};$('#itemRows').append(r);total()}
function total(){const subtotal=$$('.item-price',$('#itemRows')).reduce((s,i)=>s+(+i.value||0),0),tax=Math.floor(subtotal*.1);$('#subtotal').textContent=yen(subtotal);$('#tax').textContent=yen(tax);$('#grandTotal').textContent=yen(subtotal+tax);return{subtotal,tax,total:subtotal+tax}}
function clearEstimate(){$('#estimateForm').reset();$('#itemRows').innerHTML='';addItem('エアコン清掃',12000)}
function useCustomer(id){const c=data.customers.find(x=>x.id===id),f=$('#estimateForm');if(!c)return;f.elements.customerName.value=c.name;f.elements.phone.value=c.phone;f.elements.address.value=c.address;view('estimate')}
function openEstimate(id){const x=data.estimates.find(e=>e.id===id);if(!x)return;const s=data.settings;$('#estimateDetail').innerHTML=`<div class="detail-head"><div><p class="eyebrow">ESTIMATE ${esc(x.number)}</p><h2>御見積書</h2><p>${esc(x.customerName)} 様</p></div><button class="close-button" id="closeDetail">×</button></div><p><strong>${esc(s.companyName||'会社名未設定')}</strong><br>${esc(s.companyAddress||'')}<br>${esc(s.companyPhone||'')}</p><table class="detail-table">${x.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${yen(i.price)}</td></tr>`).join('')}<tr><td>消費税</td><td>${yen(x.tax)}</td></tr></table><div class="detail-total">合計 ${yen(x.total)}</div>${x.notes?`<p><strong>備考：</strong>${esc(x.notes)}</p>`:''}<div class="detail-actions"><button class="secondary-button" id="printEstimate">印刷・PDF</button><button class="secondary-button" id="shareEstimate">共有</button><button class="save-button" id="togglePaid">${x.paid?'未入金に戻す':'入金済みにする'}</button><button class="secondary-button danger" id="deleteEstimate">削除</button></div>`;const d=$('#detailDialog');d.showModal();$('#closeDetail').onclick=()=>d.close();$('#printEstimate').onclick=()=>print();$('#shareEstimate').onclick=()=>share(x);$('#togglePaid').onclick=async()=>{x.paid=!x.paid;await save();d.close();toast('入金状態を更新しました。')};$('#deleteEstimate').onclick=async()=>{if(confirm(x.customerName+'様の見積もりを削除しますか？')){data.estimates=data.estimates.filter(e=>e.id!==id);await save();d.close();toast('見積もりを削除しました。')}}}
async function share(x){const text=`${x.customerName} 様\n見積金額：${yen(x.total)}\n${data.settings.companyName||''}`;if(navigator.share)await navigator.share({title:'御見積書 '+x.number,text});else{await navigator.clipboard.writeText(text);toast('共有用の文章をコピーしました。')}}
function setAuth(m){authMode=m;$$('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authMode===m));$$('.register-only').forEach(e=>e.classList.toggle('hidden',m!=='register'));$('#authSubmit').textContent=m==='register'?'14日間無料で始める':'ログイン';$('#authNote').textContent=m==='register'?'クレジットカード登録は不要です。':'登録済みのアカウントでログインします。';$('#authError').textContent=''}
$('#authForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('#authSubmit');b.disabled=true;$('#authError').textContent='';if(authMode==='register'&&!f.elements.acceptedTerms.checked){$('#authError').textContent='利用規約とプライバシーポリシーへの同意が必要です。';b.disabled=false;return}try{await api('/api/auth/'+authMode,{method:'POST',body:JSON.stringify({email:f.elements.email.value.trim(),password:f.elements.password.value,companyName:f.elements.companyName.value.trim()})});f.reset();await load()}catch(x){$('#authError').textContent=x.message}finally{b.disabled=false}}
$('#estimateForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,t=total(),items=$$('.item-row',$('#itemRows')).map(r=>({name:$('.item-name',r).value.trim(),price:+$('.item-price',r).value})),now=new Date(),count=data.estimates.filter(x=>new Date(x.createdAt).getFullYear()===now.getFullYear()).length+1,x={id:crypto.randomUUID(),number:`${now.getFullYear()}-${String(count).padStart(3,'0')}`,customerName:f.elements.customerName.value.trim(),phone:f.elements.phone.value.trim(),address:f.elements.address.value.trim(),notes:f.elements.notes.value.trim(),items,...t,paid:false,createdAt:now.toISOString()};data.estimates.push(x);if(!data.customers.some(c=>c.phone&&c.phone===x.phone))data.customers.push({id:crypto.randomUUID(),name:x.customerName,phone:x.phone,address:x.address});try{await save();clearEstimate();view('home');openEstimate(x.id)}catch(err){data.estimates=data.estimates.filter(e=>e.id!==x.id);toast(err.message)}}
$('#customerForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,c={id:crypto.randomUUID(),name:f.elements.name.value.trim(),phone:f.elements.phone.value.trim(),address:f.elements.address.value.trim()};data.customers.push(c);try{await save();f.reset();$('#customerDialog').close();toast('お客さまを登録しました。')}catch(x){data.customers=data.customers.filter(v=>v.id!==c.id);toast(x.message)}}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;data.settings={companyName:f.elements.companyName.value.trim(),companyPhone:f.elements.companyPhone.value.trim(),companyAddress:f.elements.companyAddress.value.trim()};try{await save();$('#settingsDialog').close();toast('会社情報を保存しました。')}catch(x){toast(x.message)}}
$('#logoutButton').onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});$('#settingsDialog').close();load()};$('#startCheckout').onclick=async()=>{try{const r=await api('/api/billing/checkout',{method:'POST',body:'{}'});if(r.url)location.href=r.url}catch(e){$('#billingNote').textContent=e.message}};
$$('.auth-tab').forEach(b=>b.onclick=()=>setAuth(b.dataset.authMode));$$('.bottom-nav button').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>view(b.dataset.go));$$('[data-close]').forEach(b=>b.onclick=()=>$(`#${b.dataset.close}`).close());$('#addItem').onclick=()=>addItem();$('#clearEstimate').onclick=clearEstimate;$('#addCustomer').onclick=()=>$('#customerDialog').showModal();$('#customerSearch').oninput=customers;$('#openBilling').onclick=()=>$('#billingDialog').showModal();$('#openSettings').onclick=()=>{const f=$('#settingsForm');Object.entries(data.settings).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v||''});$('#settingsDialog').showModal()};$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));records()});
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').classList.remove('hidden')});$('#installApp').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').classList.add('hidden')}};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js'));addItem('エアコン清掃',12000);load();
